version: "3.7"
services:
  web:
    image: turnip_bulletin
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_DB: turnip_bulletin_development
      POSTGRES_USER: turnip_bulletin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  node_modules:
